services:
  - type: web
    name: chatty-backend
    env: node
    plan: free
    
    # Render's build and start commands
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start" # This will run "node dist/index.js" from your package.json

    # A health check path tells Render when app is ready.
    healthCheckPath: /
    
    # Environment Variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false